### ISSUE TITLE
Gas optimisation: `N` times reading on each loop of `gauges[idx]` in `_injectFunds`

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#20]
**Severity:** more costly operation the more loops they are

**Context:** currently `gauges[idx]` is read multiple times in the loop. Lines such as: 145, 146, 162 and 174.

**Recommendation:** cached the value of `gauges[idx]` at the beggining of the loop and read that value instead.

Similar as in L140 the value of `MinWaitPeriodSeconds` is being cached to save on gas costs.

```
...
address cachedGauge = gauges[idx];

Target storage targetConfig = GaugeConfigs[cachedGauge];
IChildChainGauge gauge = IChildChainGauge(cachedGauge);
...
```

## Review stage 

Balancer Maxis:
- [ ]  Acknowledge
- [x]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
See  #27

**Comment by petrovska-petro** [comment]
once #27 is merged, this issue can be closed ✅
