### ISSUE TITLE
Medium risk (M1): improper tracking of cached `balance` in `_injectFunds`

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#21]
**Severity:** medium risk. Misaccounting of actual `balance` on each loop iteration.

**Context:** currently the value of `balance` is being cached in L142, but not updated on each loop iteration after actually distributing the `targetConfig.amountPerPeriod`

**Recommendation:** it seems natural that balance should decrease on each successful loop when funds are being sent into the gauge. Account for the reduction on each iteration; e.g in L174 add:

```diff
targetConfig.lastInjectionTimestamp = uint56(block.timestamp);
targetConfig.periodNumber++;
+ balance -= targetConfig.amountPerPeriod;
```

## Review stage 

Balancer Maxis:
- [ ]  Acknowledge
- [x]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
Thank you.  This is the kind of thing I was looking for.  Let me think on this more.  Not sure it is quite so simple.  Maybe this is something we should remove if we can't have it always work.  Will spend time on it tomorrow.

**Comment by Tritium-VLK** [comment]
Ok understand now.  This isn't about keeping track of the global max per round, it's about keeping track of if we have enough gas to perform upkeep and trying to save some gas from doing a balanaceOf() each time.

Suggested the recommendation.  Everything else looks fine.   Thanks for catching that. See #26

**Comment by petrovska-petro** [comment]
once #26 is merged, this can be closed ✅
