### ISSUE TITLE
QA / Gas optimisation: handle token approval at `addRecipients` phase once

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#24]
**Severity:** informational / gas optimisation

**Context:** currently on every loop for every epoch/period while injecting there is a `forceApproval` for each gauge, while it could be only once while adding the new recipient.

**Recommendation:** if internally while gauging the gas saved impact and security concerns that infinite approval may have being added in `addRecipients`, and it is deemed secure, then we advise to add e.g:

```diff

    // enumerableSet returns false if Already Exists
    update = ActiveGauges.add(recipients[i]);
    executedPeriods = 0;
+   SafeERC20.forceApprove(
+        InjectTokenAddress,
+        recipients[i],
+        type(uint256).max
+   );

    if (!update && GaugeConfigs[recipients[i]].isActive) {
        executedPeriods = GaugeConfigs[recipients[i]].periodNumber;
    }
```

## Review stage 

Balancer Maxis:
- [x]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
We had discussed this in the past.  The issue is that things can change like the token address handled, and then you would want to revoke approvals.  This contract is meant to run on child chains (low gas).

Think it's ok to pay a little extra gas to keep approvals clean/not have that extra surface to think about.

**Comment by petrovska-petro** [comment]
we acknowledge that logic as is, it is in line with operational expectations and changes of tokens ✅ 

it can be closed
