### ISSUE TITLE
Low risk (L5): `getWeeklySpend` should consider the `programStartTimestamp` variable for each active gauge

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#33]
**Severity:** misreport weekly spend figure.

**Context:** some of the actives gauges may have a starting time way on the future, which is defined in `programStartTimestamp`, but it is not consider in the getter.

**Recommendation:** consider that variable while reporting the weekly spend in the loop. e.g:

```diff
for (uint256 i = 0; i < gauges.length; i++) {
    Target memory target = GaugeConfigs[gauges[i]];
-    if (target.periodNumber < target.maxPeriods) {
+   if (target.periodNumber < target.maxPeriods && block.timestamp >= target.programStartTimestamp) {
        weeklySpend += target.amountPerPeriod;
    }
}
```

## Review stage 

Balancer Maxis:
- [x]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [ ]  Acknowledge correction/mitigation

**Comment by petrovska-petro** [comment]
reviewed #40, awaiting feedback on comments

**Comment by Tritium-VLK** [comment]
After more thinking, I don't think we should make changes here. Consider this acknowledged.  #40 has been closed.
