### ISSUE TITLE
QA: `getReadyGauges()` has unnecessary code

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#36]
**Severity:** informational

**Context:** during the loop it is checking if `target.amountPerPeriod > maxInjectionAmount`, but given how `addRecipients` method is coded, that will never be possible, already it will revert at the time of setting the recipients.

**Recommendation:** remove that part of code in the getter. i.e:

```diff
- if (target.amountPerPeriod > maxInjectionAmount) {
-     revert ExceedsMaxInjectionAmount(
-         gaugeList[idx],
-         target.amountPerPeriod,
-         maxInjectionAmount
-     );
- }
```

## Review stage 

Balancer Maxis:
- [x]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
Just trying to make less changes/get this done.  Good comment but it's fine.  Maybe for V2.1.

**Comment by petrovska-petro** [comment]
Team acknowledged that they will like to minimise changes into the contract and this change could be added into a future version. ✅ 

We're marking this issue as "Acknowledge correction/mitigation" and closing it.
