### ISSUE TITLE
Medium risk (M3): in `changeDistributor` the distributor for an active gauge can be changed without updating the rest of storage values

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#37]
**Severity:** leads to revert in performUpkeep

**Context:** currently the owner has full freedom to update the distributor of one of the gauges within the list of the injector at any moment. see:

```
function changeDistributor(
    address gauge,
    address reward_token,
    address distributor
) external onlyOwner {
    IChildChainGauge(gauge).set_reward_distributor(
        reward_token,
        distributor
    );
}
```

**Recommendation:** changing distributor for an active gauge without updating `ActiveGauges` and/or `GaugeConfigs` will lead to revert when `performUpkeep` or `injectFunds` is executed.

It will reach the logic of injecting the token into the gauge calling:

```
gauge.deposit_reward_token(
    address(token),
    targetConfig.amountPerPeriod
);
```

Which after changing the distributor not to `address(this)` will simple revert during the loop and will be tricky revert to track down unless it is gracefully handled.

Pseudocode suggestion:

```diff
  function changeDistributor(
      address gauge,
      address reward_token,
      address distributor
  ) external onlyOwner {
+     if (ActiveGauges.contains(gauge) {
      IChildChainGauge(gauge).set_reward_distributor(
          reward_token,
          distributor
      );
+   1) remove from ActiveGauges ->> similar logic as in "removeRecipients"
+     } else {
+      IChildChainGauge(gauge).set_reward_distributor(
+          reward_token,
+          distributor
+      );
+    }
  }
```

## Review stage 

Balancer Maxis:
- [x]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [ ]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
If the injector were to become the distributor, this gauge would immediately pay out, so it is important that they are listed.

The decision to change a distributor is something that could also be made by governance/externally.  A schedule line here is an instruciton to pay in funds as soon as there is no flows at is possible.  If that schedule is no longer desired it should be removed.  Again, we are the primary user of this.  Perhaps it makes sense to go through these issues and write some docs/a faq if we intend to show this to external users.  Most externals will be using a UI, that will not offer any of the extended capacity around changing distributors, manual injections, etc.

**Comment by petrovska-petro** [comment]
From what we gather from the feedback is that primarly the maxis will handle the ops of these admin methods and in the case that:

1. a `changeDistributor` is called an injector is not anymore the distributor for `gauge[i]`; it's not a concern since the team will handle 2)
2. will also remove irrelevant schedules from the existing storage avoiding reverts during a `performUpkeep` call

if that's the case this may not be a M3, but we consider that operational methodology can be more prone to error, instead of handling directly at the core logic in `changeDistributor` as we suggested in the initial *diff**

Indeed, adding these internal operational flows into the README/docs would provide value, since other external team not as familiar as the maxis running the injector can fall into operational mistakes

marking as "Acknowledge correction/mitigation" and closing the issue as we understand that internal operations will not lead into reverts ✅
