### ISSUE TITLE
QA: `createInjector` in factory does not track on-chain childs deployed

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#5]
**Severity:** informational / analytics

**Context:** currently for tracking of all injectors deployed by the factory is forcing to have an off-chain service tracking the events emitted, indexed them and have a way to display them in a UX friendly manner; which ultimately represents another dependency of the system.

**Recommendation:** Enable directly on the factory itself ability to track all injectors deployed directly on-chain, an approach:

 - Use an array of `address[]` and leverage getters in the injector to display information from a single method. e.g: `getAllInjectors()` providing a list of all injectors deployed until present and massaging the getters from the injector itself to display information such as: `injectTokenAddress`, `KeeperAddresses`, `getFullSchedule` and alike in a single call

Up to the internal team to decide between full off-chain infrastructure or allow an on-chain tracking at the cost of being slighly more costly on storing all the injectors deployed up to date in an array.

## Review stage 

Balancer Maxis:
- [ ]  Acknowledge
- [x]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
We can talk about this internally a bit more/will.  My impression is that the factory is permissionless and anyone can launch anything, even though it is not configured/functional.  The offchain data/registry can be maintained such that only injectors that are actually configured/working properly are presented to users. 

That being said, maybe there are reasons to be able to verify that an injector came from this factory onchain. Will bring up in our dev meeting.

**Comment by Tritium-VLK** [comment]
see #15

**Comment by petrovska-petro** [comment]
once #15 is merged, indeed this issue can be closed ✅
