### ISSUE TITLE
Test: `it("should checkSufficientBalances and return false"` unclear outcome on `expect`

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#9]
**Severity:** potentially unexpected returned value in `getBalanceDelta` or miswording in test suite

**Context:** it seems that the test would like to signal that actually there is sufficient balances in the injector to cover the actual period. But it is checking for being negative or equal to zero, by the Natspec comments seems that negative value signals that there is an actual deficit. Is this behaviour desired?

**Recommendation:** to ensure that `getBalanceDelta` is returning the expected values we will advise to cover 3 scenarios in the suite:

1. deficit
2. exact balance
3. surplus

Also, it seems worth to give a reconsideration on wording in the Natspec comments or the test suite description, as while reviewing intention was not 100% clear.

## Review stage 

Balancer Maxis:
- [ ]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
@Hyferion Can you please take a look/respond to this one?

**Comment by petrovska-petro** [comment]
@Hyferion could you please provide feedback on this issue to decide in which state is?
